# Generated by Django 6.0.4 on 2026-05-24 02:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_transaction_transaction_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'category', 'month_year')},
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nama tabungan, misal: Dana Darurat', max_length=100)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('deadline', models.DateField(blank=True, help_text='Target tanggal selesai', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(choices=[('#4A90D9', 'Blue'), ('#27AE60', 'Green'), ('#E67E22', 'Orange'), ('#9B59B6', 'Purple'), ('#E74C3C', 'Red'), ('#1ABC9C', 'Teal'), ('#F39C12', 'Yellow'), ('#2C3E50', 'Dark')], default='#4A90D9', max_length=10)),
                ('icon', models.CharField(default='savings', help_text='Material icon name', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
