# Generated by Django 6.0.4 on 2026-06-19 14:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_budget_unique_together_savingsgoal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('asset_type', models.CharField(max_length=10)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('price_change_24h', models.DecimalField(blank=True, decimal_places=2, help_text='Perubahan harga 24 jam (%)', max_digits=10, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(default='api', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Price Caches',
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('stock', 'Saham'), ('crypto', 'Cryptocurrency')], max_length=10)),
                ('symbol', models.CharField(help_text='Ticker symbol (e.g., BBCA, BTC)', max_length=20)),
                ('name', models.CharField(help_text='Nama asset (e.g., Bank BCA, Bitcoin)', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=8, help_text='Jumlah yang dimiliki (bisa desimal untuk crypto)', max_digits=20)),
                ('buy_price', models.DecimalField(decimal_places=2, help_text='Harga beli rata-rata per unit', max_digits=20)),
                ('purchase_date', models.DateField(help_text='Tanggal pembelian pertama')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'symbol', 'asset_type')},
            },
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('buy', 'Beli'), ('sell', 'Jual')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Harga per unit', max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('transaction_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.investment')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
    ]
